const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const vm=require('vm');
const ctx={window:{},console,structuredClone:global.structuredClone,Date,Math,RegExp,String,Set,Map};ctx.global=ctx;vm.createContext(ctx);['edc_site/admin/seating-plan/js/types.js','edc_site/admin/seating-plan/js/seating-core.js','edc_site/admin/seating-plan/js/import-export.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f}));
const C=ctx.window.SeatingCore,IE=ctx.window.SeatingImportExport;
test('imports CSV guest list',()=>{const p=IE.parseDelimited('Full Name,Country,VIP\nJane Doe,DE,yes');const a=IE.analyzeRows(p.rows);assert.equal(a.guests.length,1);assert.equal(a.guests[0].firstName,'Jane');assert.equal(a.guests[0].vip,true)});
test('detects duplicate guests',()=>{const d=C.duplicateGuests([C.normalizeGuest({fullName:'Jane Doe'}),C.normalizeGuest({fullName:'Jane Doe'})]);assert.equal(d.length,1)});
test('assigns guest to a seat once',()=>{let p=C.createPlan();const g=C.normalizeGuest({fullName:'John Smith'}),t=C.createTable(1,8);p.guests=[g];p.tables=[t];p=C.assignGuest(p,g.id,t.id,1);p=C.assignGuest(p,g.id,t.id,2);assert.equal(p.assignments.length,1);assert.equal(p.assignments[0].seatNumber,2)});
test('swaps seats',()=>{let p=C.createPlan();const a=C.normalizeGuest({fullName:'Ann A'}),b=C.normalizeGuest({fullName:'Bob B'}),t=C.createTable(1,8);p.guests=[a,b];p.tables=[t];p=C.assignGuest(p,a.id,t.id,1);p=C.assignGuest(p,b.id,t.id,2);p=C.swapOrAssign(p,a.id,t.id,2);assert.equal(p.assignments.find(x=>x.guestId===a.id).seatNumber,2);assert.equal(p.assignments.find(x=>x.guestId===b.id).seatNumber,1)});
test('removes assignment',()=>{let p=C.createPlan();const g=C.normalizeGuest({fullName:'John Smith'}),t=C.createTable(1,8);p.guests=[g];p.tables=[t];p=C.assignGuest(p,g.id,t.id,1);p=C.unassignGuest(p,g.id);assert.equal(p.assignments.length,0)});
test('calculates available seats',()=>{let p=C.createPlan();const g=C.normalizeGuest({fullName:'John Smith'}),t=C.createTable(1,8);p.guests=[g];p.tables=[t];p=C.assignGuest(p,g.id,t.id,1);assert.equal(C.availableSeats(p),7)});

test('imports Excel-style headers case insensitively',()=>{const a=IE.analyzeRows([{'Full name':'Alice Example','Company':'EDC','VIP':'1'}]);assert.equal(a.guests.length,1);assert.equal(a.guests[0].firstName,'Alice');assert.equal(a.guests[0].company,'EDC');assert.equal(a.guests[0].vip,true)});


test('import/export helpers work when loaded before seating core',()=>{const lateCtx={window:{},console,structuredClone:global.structuredClone,Date,Math,RegExp,String,Set,Map};lateCtx.global=lateCtx;vm.createContext(lateCtx);['edc_site/admin/seating-plan/js/types.js','edc_site/admin/seating-plan/js/import-export.js','edc_site/admin/seating-plan/js/seating-core.js'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),lateCtx,{filename:f}));const lateIE=lateCtx.window.SeatingImportExport;const a=lateIE.analyzeRows([{'Full Name':'Late Loaded','VIP':'yes'}]);assert.equal(a.guests.length,1);assert.equal(a.guests[0].firstName,'Late');assert.equal(lateIE.normalizeHeader('Full Name'),'fullName')});
