'use strict';
(function(exports){
 const getCore=()=>exports.SeatingCore;
 const fields=['fullName','firstName','lastName','country','company','position','group','language','vip','notes'];
 const aliases={'full name':'fullName','fullname':'fullName','name':'fullName','guest':'fullName','guest name':'fullName','first name':'firstName','firstname':'firstName','first':'firstName','last name':'lastName','lastname':'lastName','surname':'lastName','last':'lastName','country':'country','company':'company','position':'position','title':'position','group':'group','table':'group','language':'language','vip':'vip','notes':'notes','note':'notes'};
 function normalizeHeader(header){const C=getCore();return aliases[C.clean(header).toLowerCase()]||C.clean(header)}
 function normalizeRow(row){const out={};Object.entries(row||{}).forEach(([key,value])=>{out[normalizeHeader(key)]=value});return out}
 function parseDelimited(text){const lines=text.split(/\r?\n/).map(l=>l.trim()).filter(Boolean);if(!lines.length)return {headers:[],rows:[]};const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const split=l=>l.match(/("[^"]*(""[^"]*)*"|[^,;]+)/g)?.map(v=>v.replace(/^"|"$/g,'').replace(/""/g,'"').trim())||[];const raw=split(lines[0]);const headers=raw.map(normalizeHeader);const rows=lines.slice(1).map(l=>{const vals=split(l),row={};headers.forEach((h,i)=>row[h]=vals[i]||'');return row});return {headers,rows}}
 function parseTxt(text){const C=getCore();const rows=text.split(/\r?\n/).map(C.clean).filter(Boolean).map(fullName=>({fullName}));return {headers:['fullName'],rows}}
 function analyzeRows(rows,existing=[]){const C=getCore();const guests=rows.map(normalizeRow).map(C.normalizeGuest).filter(g=>C.guestName(g));const names=new Set(existing.map(g=>C.guestName(g).toLowerCase()));const dup=guests.filter((g,i)=>names.has(C.guestName(g).toLowerCase())||guests.findIndex(x=>C.guestName(x).toLowerCase()===C.guestName(g).toLowerCase())!==i);const invalid=guests.filter(g=>!g.firstName||!g.lastName);return {guests,duplicates:dup,invalid}}
 function guestsByTable(plan){return plan.tables.map(t=>({table:t,guests:plan.assignments.filter(a=>a.tableId===t.id).sort((a,b)=>a.seatNumber-b.seatNumber).map(a=>({...plan.guests.find(g=>g.id===a.guestId),seatNumber:a.seatNumber}))}))}
 function toCsv(plan){const C=getCore();const rows=[['Full Name','First Name','Last Name','Country','Company','Group','VIP','Table Number','Seat Number']];plan.guests.forEach(g=>{const a=plan.assignments.find(x=>x.guestId===g.id),t=a&&plan.tables.find(x=>x.id===a.tableId);rows.push([C.guestName(g),g.firstName,g.lastName,g.country||'',g.company||'',g.group||'',g.vip?'Yes':'No',t?String(t.number):'',a?String(a.seatNumber):''])});return rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n')}
 exports.SeatingImportExport={fields,parseDelimited,parseTxt,analyzeRows,guestsByTable,toCsv,normalizeHeader,normalizeRow};
})(window);
if(typeof module!=='undefined') module.exports=global.window?window.SeatingImportExport:{};
